export enum CategorySortType {
  UNSORTED = 'UNSORTED',
  SORT_BY_NAME_ASC = 'SORT_BY_NAME_ASC',
  SORT_BY_NAME_DESC = 'SORT_BY_NAME_DESC',
  SORT_BY_COUNT_ASC = 'SORT_BY_COUNT_ASC',
  SORT_BY_COUNT_DESC = 'SORT_BY_COUNT_DESC',
}
