/*
 * Copyright (c) Minh Loi.
 *
 * This file is part of Ulangi which is released under GPL v3.0.
 * See LICENSE or go to https://www.gnu.org/licenses/gpl-3.0.txt
 */

export enum ErrorCode {
  GENERAL__NETWORK_ERROR = 'GENERAL_ERROR_CODE/NETWORK_ERROR',
  GENERAL__UNAUTHENTICATED = 'GENERAL_ERROR_CODE/UNAUTHENTICATED',
  GENERAL__INVALID_REQUEST = 'GENERAL_ERROR_CODE/INVALID_REQUEST',
  GENERAL__INVALID_DATA = 'GENERAL_ERROR_CODE/INVALID_DATA',
  GENERAL__SERVER_ERROR = 'GENERAL_ERROR_CODE/SERVER_ERROR',
  GENERAL__USER_CANCELLED = 'GENERAL_ERROR_CODE/USER_CANCELLED',
  GENERAL__UNKNOWN_ERROR = 'GENERAL_ERROR_CODE/UNKNOWN_ERROR',
  GENERAL__FAILED_TO_GRANT_PERMISSION = 'GENERAL__FAILED_TO_GRANT_PERMISSION',

  ATOM__INSUFFICIENT_VOCABULARY = 'ATOM_ERROR_CODE/INSUFFICIENT_VOCABULARY',

  REFLEX__INSUFFICIENT_VOCABULARY = 'REFLEX_ERROR_CODE/INSUFFICIENT_VOCABULARY',

  DATABASE__CONNECT_FAILED = 'DATABASE_ERROR_CODE/CONNECT_FAILED',

  DICTIONARY__NO_RESULTS = 'DICTIONARY_ERROR_CODE/NO_RESULTS',
  DICTIONARY__UNSUPPORTED = 'DICTIONARY_ERROR_CODE/UNSUPPORTED',
  DICTIONARY__SPECIFIC_LANAGUAGE_REQUIRED = 'DICTIONARY_ERROR_CODE/SPECIFIC_LANGUAGE_REQUIRED',

  TRANSLATION__UNSUPPORTED_LANGUAGE = 'TRANSLATION_ERROR_CODE/UNSUPPORTED_LANGUAGE',
  TRANSLATION__UNSUPPORTED_TRANSLATOR = 'TRANSLATION_ERROR_CODE/UNSUPPORTED_TRANSLATOR',
  TRANSLATION__SPECIFIC_LANGUAGE_REQUIRED = 'TRANSLATION_ERROR_CODE/SPECIFIC_LANGUAGE_REQUIRED',
  TRANSLATION__SAME_SOURCE_DESTINATION_LANGUAGE = 'TRANSLATION_ERROR_CODE/SAME_SOURCE_DESTINATION_LANGUAGE',

  SEARCH__NO_RESULTS = 'SEARCH_ERROR_CODE/NO_RESULTS',

  QUIZ__INSUFFICIENT_VOCABULARY = 'QUIZ_ERROR_CODE/INSUFFICIENT_VOCABULARY',

  DEFINITION__EMPTY_MEANING = 'DEFINITION_ERROR_CODE/EMPTY_MEANING',

  VOCABULARY__EMPTY_VOCABULARY_TEXT = 'VOCABULARY_ERROR_CODE/EMPTY_VOCABULARY_TEXT',
  VOCABULARY__NO_DEFINITIONS = 'VOCABULARY_ERROR_CODE/NO_DEFINITIONS',
  VOCABULARY__LANGUAGE_NOT_SUPPORTED_FOR_SYNTHESIZE_SPEECH = 'VOCABULARY_ERROR_CODE/LANGUAGE_NOT_SUPPORTED_FOR_SYNTHESIZE_SPEECH',
  VOCABULARY__CANNOT_SYNTHESIZE_SPEECH = 'VOCABULARY_ERROR_CODE/CANNOT_SYNTHESIZE_SPEECH',

  SET__EMPTY_SET_NAME = 'SET_ERROR_CODE/EMPTY_SET_NAME',

  USER__USER_NOT_FOUND = 'USER_ERROR_CODE/USER_NOT_FOUND',
  USER__USER_DISABLED = 'USER_ERROR_CODE/USER_DISABLED',
  USER__INVALID_EMAIL = 'USER_ERROR_CODE/INVALID_EMAIL',
  USER__EMAIL_NOT_FOUND = 'USER_ERROR_CODE/EMAIL_NOT_FOUND',
  USER__EMAIL_ALREADY_REGISTERED = 'USER_ERROR_CODE/EMAIL_ALREADY_REGISTERED',
  USER__WRONG_EMAIL_OR_PASSWORD = 'USER_ERROR_CODE/WRONG_EMAIL_OR_PASSWORD',
  USER__WRONG_PASSWORD = 'USER_ERROR_CODE/WRONG_PASSWORD',
  USER__WEAK_PASSWORD = 'USER_ERROR_CODE/WEAK_PASSWORD',
  USER__CONFIRM_PASSWORD_MISMATCHED = 'USER_ERROR_CODE/CONFIRM_PASSWORD_MISMATCHED',

  WRITING__INSUFFICIENT_VOCABULARY = 'WRITING_ERROR_CODE/INSUFFICIENT_VOCABULARY',

  SPACED_REPETITION__INSUFFICIENT_VOCABULARY = 'SPACED_REPETITION_ERROR_CODE/INSUFFICIENT_VOCABULARY',

  IAP__INVALID_RECEIPT = 'IAP__INVALID_RECEIPT',
  IAP__NO_PURCHASES = 'IAP__NO_PURCHASES',
  IAP__PURCHASES_ALREADY_APPLIED = 'IAP__PURCHASES_ALREADY_APPLIED',
  IAP__PURCHASES_ALREADY_APPLIED_TO_OTHER_ACCOUNTS = 'IAP__PURCHASES_ALREADY_APPLIED_TO_OTHER_ACCOUNTS',

  AD__ALREADY_INITIALIZED = 'AD__ALREADY_INITIALIZED',
  AD__AD_CONSENT_REQUIRED = 'AD__AD_CONSENT_REQUIRED',
  AD__AD_NOT_YET_LOADED = 'AD__AD_NOT_YET_LOADED',
  AD__INTERNAL_ERROR = 'AD__INTERNAL_ERROR',
  AD__INVALID_REQUEST = 'AD__INVALID_REQUEST',
  AD__NETWORK_ERROR = 'AD__NETWORK_ERROR',
  AD__NO_FILL = 'AD__NO_FILL',

  FLASHCARD_PLAYER__INSUFFICIENT_VOCABULARY = 'FLASHCARD_PLAYER__INSUFFICIENT_VOCABULARY',

  REMINDER__PERMISSION_REQUIRED = 'REMINDER__PERMISSION_REQUIRED',
}
