export enum VocabularySortType {
  UNSORTED = 'UNSORTED',
  SORT_BY_NAME_ASC = 'SORT_BY_NAME_ASC',
  SORT_BY_NAME_DESC = 'SORT_BY_NAME_DESC',
  SORT_BY_CREATION_TIME_ASC = 'SORT_BY_CREATION_TIME_ASC',
  SORT_BY_CREATION_TIME_DESC = 'SORT_BY_CREATION_TIME_DESC',
  SORT_BY_UPDATE_TIME_ASC = 'SORT_BY_UPDATE_TIME_ASC',
  SORT_BY_UPDATE_TIME_DESC = 'SORT_BY_UPDATE_TIME_DESC',
}
