/*
 * Copyright (c) Minh Loi.
 *
 * This file is part of Ulangi which is released under GPL v3.0.
 * See LICENSE or go to https://www.gnu.org/licenses/gpl-3.0.txt
 */

export const CategoryBulkActionMenuIds = {
  ACTION_MENU: 'CATEGORY_BULK_ACTION_MENU',
  SELECT_ALL_FETCHED_CATEGORIES_BTN: 'SELECT_ALL_FETCHED_CATEGORIES_BTN',
  LEARN_WITH_SPACED_REPPETITION_BTN: 'LEARN_WITH_SPACED_REPPETITION_BTN',
  LEARN_WITH_WRITING_BTN: 'LEARN_WITH_WRITING_BTN',
  QUIZ_BTN: 'QUIZ_BTN',
  PLAY_WITH_REFLEX_BTN: 'PLAY_WITH_REFLEX_BTN',
  PLAY_WITH_ATOM_BTN: 'PLAY_WITH_ATOM_BTN',
  AUTOPLAY_BTN: 'AUTOPLAY_BTN',
};
