/*
 * Copyright (c) Minh Loi.
 *
 * This file is part of Ulangi which is released under GPL v3.0.
 * See LICENSE or go to https://www.gnu.org/licenses/gpl-3.0.txt
 */

export const DiscoverScreenIds = {
  SCREEN: 'DISCOVER_SCREEN',
  TOP_BAR: 'DISCOVER_TOP_BAR',
  TIP_BTN: 'TIP_BTN',
  UNSUPPORTED_SECTION: 'UNSUPPORTED_SECTION',
  SHOW_SET_SELECTION_MENU_BTN: 'SHOW_SET_SELECTION_MENU_BTN',
  ERROR: 'ERROR',
  NO_RESULTS: 'NO_RESULTS',
  SEARCH_INPUT: 'SEARCH_INPUT',
  CLEAR_SEARCH_INPUT: 'CLEAR_SEARCH_INPUT',

  VIEW_ALL_SETS_BTN: 'VIEW_ALL_SETS_BTN',
  VIEW_SEARCH_SET_RESULT_BTN: 'VIEW_SEARCH_SET_RESULT_BTN',
  VIEW_TRANSLATION_AND_SEARCH_VOCABULARY_RESULT_BTN:
    'VIEW_TRANSLATION_AND_SEARCH_VOCABULARY_RESULT_BTN',

  PUBLIC_SET_LIST: 'PUBLIC_SET_LIST',
  TRANSLATION_AND_PUBLIC_VOCABULARY_LIST:
    'TRANSLATION_AND_PUBLIC_VOCABULARY_LIST',
};
