/*
 * Copyright (c) Minh Loi.
 *
 * This file is part of Ulangi which is released under GPL v3.0.
 * See LICENSE or go to https://www.gnu.org/licenses/gpl-3.0.txt
 */

export const ManageScreenIds = {
  SCREEN: 'MANAGE_SCREEN',
  TOP_BAR: 'MANAGE_TOP_BAR',
  SHOW_SET_SELECTION_MENU_BTN: 'SHOW_SET_SELECTION_MENU_BTN',
  SHOW_CATEGORY_SORT_MENU_BTN: 'SHOW_CATEGORY_SORT_MENU_BTN',
  SHOW_VOCABULARY_FILTER_MENU_BTN: 'SHOW_VOCABULARY_FILTER_MENU_BTN',
  QUICK_TUTORIAL_BTN: 'QUICK_TUTORIAL_BTN',
  ADD_VOCABULARY_BTN: 'ADD_VOCABULARY_BTN',
  SEARCH_BTN: 'SEARCH_BTN',
  CATEGORY_LIST: 'CATEGORY_LIST',
  REFRESH_BTN: 'REFRESH_BTN',
  SESSION_EXPIRED_DIALOG: 'SESSION_EXPIRED_DIALOG',
};
