/*
 * Copyright (c) Minh Loi.
 *
 * This file is part of Ulangi which is released under GPL v3.0.
 * See LICENSE or go to https://www.gnu.org/licenses/gpl-3.0.txt
 */

export const MoreScreenIds = {
  SCREEN: 'MORE_SCREEN',
  TOP_BAR: 'MORE_TOP_BAR',
  MORE_SCROLL_VIEW: 'MORE_SCROLL_VIEW',
  SET_UP_ACCOUNT_BTN: 'SET_UP_ACCOUNT_BTN',
  SECURITY_BTN: 'SECURITY_BTN',
  MEMBERSHIP_BTN: 'MEMBERSHIP_BTN',
  REMINDER_BTN: 'REMINDER_BTN',
  DARK_MODE_BTN: 'DARK_MODE_BTN',
  SYNCHRONIZER_BTN: 'SYNCHRONIZER_BTN',
  SET_MANAGEMENT_BTN: 'SET_MANAGEMENT_BTN',
  AUTO_ARCHIVE_BTN: 'AUTO_ARCHIVE_BTN',
  SYNC_WITH_GOOGLE_SHEETS_BTN: 'SYNC_WITH_GOOGLE_SHEETS_BTN',
  FEATURE_REQUEST_BTN: 'FEATURE_REQUEST_BTN',
  REPORT_A_BUG_BTN: 'REPORT_A_BUG_BTN',
  CONTACT_SUPPORT_BTN: 'CONTACT_SUPPORT_BTN',
  VERSION_BTN: 'VERSION_BTN',
  AD_CONSENT_BTN: 'AD_CONSENT_BTN',
  DATA_SHARING_BTN: 'DATA_SHARING_BTN',
  TERMS_OF_SERVICE_BTN: 'TERMS_OF_SERVICE_BTN',
  PRIVACY_POLICY_BTN: 'PRIVACY_POLICY_BTN',
  OPEN_SOURCE_PROJECTS_BTN: 'OPEN_SOURCE_PROJECTS_BTN',
  RATE_THIS_APP_BTN: 'RATE_THIS_APP_BTN',
  WHATS_NEW_BTN: 'WHATS_NEW_BTN',
  FOLLOW_US_ON_TWITTER_BTN: 'FOLLOW_US_ON_TWITTER_BTN',
  FOLLOW_US_ON_INSTAGRAM_BTN: 'FOLLOW_US_ON_INSTAGRAM_BTN',
  JOIN_OUR_COMMUNITY_BTN: 'JOIN_OUR_COMMUNITY_BTN',
  QUICK_TUTORIAL_BTN: 'QUICK_TUTORIAL_BTN',
  LOG_OUT_BTN: 'LOG_OUT_BTN',
  YES_BTN: 'YES_BTN',
  NO_BTN: 'NO_BTN',
};
