/*
 * Copyright (c) Minh Loi.
 *
 * This file is part of Ulangi which is released under GPL v3.0.
 * See LICENSE or go to https://www.gnu.org/licenses/gpl-3.0.txt
 */

export const VocabularyFormIds = {
  VOCABULARY_TEXT_INPUT: 'VOCABULARY_TEXT_INPUT',
  LOOK_UP_BTN: 'LOOK_UP_BTN',
  SELECT_TAB_BTN_BY_TAB_TYPE: (tab: 'Editor' | 'Preview'): string =>
    'SELECT_TAB_BTN_BY_TAB_TYPE_' + tab,
  VOCABULARY_EXTRA_FIELDS_BTN: 'VOCABULARY_EXTRA_FIELDS_BTN',
  DEFINITION_EXTRA_FIELDS_BTN_BY_INDEX: (index: number): string =>
    'DEFINITION_EXTRA_FIELDS_BTN_BY_INDEX_' + index,
  DELETE_DEFINITION_BTN_BY_INDEX: (index: number): string =>
    'DELETE_DEFINITION_BTN_BY_INDEX_' + index,
  ADD_DEFINITION_BTN: 'ADD_DEFINITION_BTN',
  CANCEL_BTN: 'CANCEL_BTN',
  DELETE_BTN: 'DELETE_BTN',
  MEANING_INPUT_BY_INDEX: (index: number): string =>
    'MEANING_INPUT_BY_INDEX_' + index,
  EDIT_CATEGORY_BTN: 'EDIT_CATEGORY_BTN',
  DICTIONARY_LIST: 'DICTIONARY_LIST',
  EXTRA_FIELD_LIST: 'EXTRA_FIELD_LIST',
  CLOSE_PICKER_BTN: 'CLOSE_PICKER_BTN',
  ADD_EXTRA_FIELD_BTN_BY_TEXT: (text: string): string =>
    'ADD_EXTRA_FIELD_BTN_BY_TEXT_' + text,
  ADD_DEFINITION_FROM_TRANSLATION_BY_INDEX: (index: number): string =>
    'ADD_DEFINITION_FROM_TRANSLATION_BY_INDEX_' + index,
  ADD_DEFINITION_FROM_DICTIONARY_BY_INDEX: (index: number): string =>
    'ADD_DEFINITION_FROM_DICTIONARY_BY_INDEX_' + index,
  DICTIONARY_SPECIFIC_LANGUAGE_REQUIRED:
    'DICTIONARY_SPECIFIC_LANGUAGE_REQUIRED',
  TRANSLATION_SAME_SOURCE_DESTINATION: 'TRANSLATION_SAME_SOURCE_DESTINATION',
  TRANSLATION_SPECIFIC_LANGUAGE_REQUIRED:
    'TRANSLATION_SPECIFIC_LANGUAGE_REQUIRED',
  TRANSLATE_WITH_GOOGLE_BTN: 'TRANSLATE_WITH_GOOGLE_BTN',
};
