/*
 * Copyright (c) Minh Loi.
 *
 * This file is part of Ulangi which is released under GPL v3.0.
 * See LICENSE or go to https://www.gnu.org/licenses/gpl-3.0.txt
 */

export const WritingFormIds = {
  SKIP_BTN: 'SKIP_BTN',
  NEXT_BTN: 'NEXT_BTN',
  HINT_TEXT: 'HINT_TEXT',
  HINT_BTN: 'HINT_BTN',
  GIVEN_DEFINITION: 'GIVEN_DEFINITION',
  ANSWER_INPUT: 'ANSWER_INPUT',
  DISABLE_BTN: 'DISABLE_BTN',
  USE_HINT_SIDE_EFFECT_BTN: 'USE_HINT_SIDE_EFFECT_BTN',
  CONFIRM_DISABLE_BTN: 'CONFIRM_DISABLE_BTN',
  CANCEL_DISABLE_BTN: 'CANCEL_DISABLE_BTN',
  ANSWER_IS_CORRECT: 'ANSWER_IS_CORRECT',
  ANSWER_IS_PARTIALLY_CORRECT: 'ANSWER_IS_PARTIALLY_CORRECT',
  ANSWER_IS_INCORRECT: 'ANSWER_IS_INCORRECT',
};
